### MAIN WINDOW GUI
MAIN_WINDOW_TITLE: str = "Tumor Simulation Program"
MAIN_WINDOW_INITIAL_WIDTH: int = 1300
MAIN_WINDOW_INITIAL_HEIGHT: int = 880

### MAIN WINDOW UPPER MENU BAR
MAIN_WINDOW_MENU_EXIT_TITLE: str = "Exit"
MAIN_WINDOW_MENU_SETTINGS_TITLE: str = "Settings"
MAIN_WINDOW_MENU_ABOUT_TITLE: str = "About"
MAIN_WINDOW_MENU_DOCUMMENTATION_TITLE: str = "Docummentation"

### MAIN WINDOW MENU CONTROL
MENU_ABOUT_TAB_TITLE: str = "About Program"
MENU_ABOUT_TAB_MESSAGE: str = (
    "Wroten by Stanislaw Krasichynsky \n For Bachelor Dimploma Project \n 2024"
)

MENU_EXIT_TAB_TITLE: str = "Exit Program"
MENU_EXIT_TAB_MESSAGE: str = "Are you sure you want to exit?"

MENU_DOCUMMENTATION_URL: str = (
    "https://github.com/thekrasich/Cancer_Tumor_Simulation_Program"
)

### SETTINGS GUI
SETTINGS_WINDOW_TITLE: str = "Program Settings"
SETTINGS_WINDOW_INITIAL_WIDTH: int = 1000
SETTINGS_WINDOW_INITIAL_HEIGHT: int = 680

### PLOTTER
PLOTTER_WIDTH_INCHES: float = 7.6
PLOTTER_HEIGTH_INCHES: float = 7.6
PLOTTER_X_PLACEMENT: float = 0.38
PLOTTER_Y_PLACEMENT: float = 0.1

### MAIN WINDOW TABS
MAIN_WINDOW_TAB_AREA_TITLE: str = "Area"
MAIN_WINDOW_TAB_MESH_TITLE: str = "Mesh"
MAIN_WINDOW_TAB_MATH_MODEL_TITLE: str = "Mathematical Model"
MAIN_WINDOW_TAB_START_TITLE: str = "Start Panel"
MAIN_WINDOW_TAB_GENERIC_BUTTON_WIDTH: int = 430
MAIN_WINDOW_TAB_GENERIC_BUTTON_HEIGTH: int = 65

### Tabs sections.
